# Generated by Django 4.2.6 on 2023-10-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDate', models.DateField(verbose_name='DepartureDate')),
                ('ReturnDate', models.DateField(verbose_name='ReturnDate')),
                ('City', models.CharField(max_length=30, verbose_name='City')),
                ('State', models.CharField(max_length=30, verbose_name='State')),
                ('Country', models.CharField(max_length=30, verbose_name='Country')),
                ('NumberOfTraveler', models.IntegerField(verbose_name='NumberOfTraveler')),
                ('BudgeMin', models.IntegerField(blank=True, verbose_name='BudgeMin')),
                ('BudgetMax', models.IntegerField(verbose_name='BudgetMax')),
            ],
        ),
    ]
