name: ishtiaq_khan_github_action

on:
  push:
    branches:
      - ishtiaq_tests
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
      working-directory: travel_itinerary

    - name: Run unit and integration tests
      run: python manage.py test travel_itinerary_app.tests -v 2
      working-directory: travel_itinerary

    - name: Generate code coverage report
      run: |
        pip install coverage
        coverage run --source=travel_itinerary_app manage.py test travel_itinerary_app.tests
        coverage report
      working-directory: travel_itinerary

    - name: Start the site
      run: python manage.py runserver &
      working-directory: travel_itinerary


    - name: Execute end-2-end tests
      env:
       DJANGO_SETTINGS_MODULE: travel_itinerary.settings 
      run: |
        pip install selenium
        python manage.py test travel_itinerary_app.tests.test_e2e
      working-directory: travel_itinerary